<a href="https://colab.research.google.com/github/mingmingbupt/tensorflow/blob/master/text_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

print(tf.__version__)
print(sys.version_info)
for module in mpl, np, pd, sklearn, tf, keras:
    print(module.__name__, module.__version__)

2.2.0
sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)
matplotlib 3.2.1
numpy 1.18.4
pandas 1.0.3
sklearn 0.22.2.post1
tensorflow 2.2.0
tensorflow.keras 2.3.0-tf


In [3]:
# https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt
input_filepath = "./shakespeare.txt"
text = open(input_filepath, 'r').read()

print(len(text))
print(text[0:100])

FileNotFoundError: ignored

In [4]:
# 1. generate vocab 生成词表
# 2. build mapping char->id 生成映射
# 3. data -> id_data 数据都转成id
# 4. abcd -> bcd<eos> 对数据做变换，定义他的输入输出。他的输入可能及时文本比如abcd， 输出就是他的下一个文本。a的下一个就是b,b的下一个就是c，c的下一个就是d
# 预测下一个字符的模型，才可以一个字符一个字符的生成下一个字符的模型
vocab = sorted(set(text)) # 词表
print(len(vocab)) # 词表大小
print(vocab)

NameError: ignored

In [0]:
char2idx = {char:idx for idx, char in enumerate(vocab)}
print(char2idx)

{'x': 62, 'Z': 38, 'F': 18, 'T': 32, 'n': 52, 'A': 13, '3': 9, 'b': 40, 'C': 15, 'e': 43, 'q': 55, 'K': 23, 'z': 64, 'E': 17, "'": 5, 'Y': 37, 'd': 42, 'W': 35, 'S': 31, 'p': 54, 'I': 21, 'J': 22, 'y': 63, 'X': 36, 'G': 19, '$': 3, 'N': 26, 'w': 61, 'i': 47, ' ': 1, 'h': 46, 'j': 48, 'o': 53, ',': 6, '-': 7, 'H': 20, 's': 57, 'U': 33, '!': 2, 'g': 45, 'v': 60, ':': 10, 'r': 56, 'u': 59, 'V': 34, 'O': 27, 'P': 28, ';': 11, 'L': 24, '.': 8, 'B': 14, '\n': 0, 'k': 49, 'Q': 29, 'c': 41, 't': 58, 'M': 25, 'R': 30, 'f': 44, 'm': 51, 'l': 50, '&': 4, '?': 12, 'a': 39, 'D': 16}


In [0]:
idx2char = np.array(vocab)
print(idx2char)

['\n' ' ' '!' '$' '&' "'" ',' '-' '.' '3' ':' ';' '?' 'A' 'B' 'C' 'D' 'E'
 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R' 'S' 'T' 'U' 'V' 'W'
 'X' 'Y' 'Z' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o'
 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


In [0]:
text_as_int = np.array([char2idx[c] for c in text])
print(text_as_int[0:10])
print(text[0:10]) #把数据都转换成id了

[18 47 56 57 58  1 15 47 58 47]
First Citi


In [0]:
def split_input_target(id_text):
    """
    abcde -> abcd, bcde
    """
    return id_text[0:-1], id_text[1:]

char_dataset = tf.data.Dataset.from_tensor_slices(text_as_int)
seq_length = 100
seq_dataset = char_dataset.batch(seq_length + 1, # 这个batch为了把字符变成句子
                                 drop_remainder = True) #最后的batch如果不够就丢掉
for ch_id in char_dataset.take(2):
    print(ch_id, idx2char[ch_id.numpy()])

for seq_id in seq_dataset.take(2):
    print(seq_id)
    print(repr(''.join(idx2char[seq_id.numpy()])))

tf.Tensor(18, shape=(), dtype=int64) F
tf.Tensor(47, shape=(), dtype=int64) i
tf.Tensor(
[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59  1], shape=(101,), dtype=int64)
'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '
tf.Tensor(
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1 49], shape=(101,), dtype=int64)
'are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you k'


In [0]:
seq_dataset = seq_dataset.map(split_input_target)

for item_input, item_output in seq_dataset.take(2):
    print(item_input.numpy())
    print(item_output.numpy())

[18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43
  1 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43
 39 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49
  6  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10
  0 37 53 59]
[47 56 57 58  1 15 47 58 47 64 43 52 10  0 14 43 44 53 56 43  1 61 43  1
 54 56 53 41 43 43 42  1 39 52 63  1 44 59 56 58 46 43 56  6  1 46 43 39
 56  1 51 43  1 57 54 43 39 49  8  0  0 13 50 50 10  0 31 54 43 39 49  6
  1 57 54 43 39 49  8  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0
 37 53 59  1]
[39 56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1
 58 53  1 42 47 43  1 58 46 39 52  1 58 53  1 44 39 51 47 57 46 12  0  0
 13 50 50 10  0 30 43 57 53 50 60 43 42  8  1 56 43 57 53 50 60 43 42  8
  0  0 18 47 56 57 58  1 15 47 58 47 64 43 52 10  0 18 47 56 57 58  6  1
 63 53 59  1]
[56 43  1 39 50 50  1 56 43 57 53 50 60 43 42  1 56 39 58 46 43 56  1 58
 53  1 42

In [0]:
batch_size = 64
buffer_size = 10000

seq_dataset = seq_dataset.shuffle(buffer_size).batch(
    batch_size, drop_remainder=True) #最后一组不够的话就丢弃掉


In [0]:
vocab_size = len(vocab)
embedding_dim = 256
rnn_units = 1024

# vocab_size此表大小， 因为我预测的是下一个字符，我需要预测出来每个字符的概率是多少
# embedding_dim 词表比较小，embeding设成大些 256
# run_units RNN的宽度，因为vocab_size较小，设的大一些，设置成1024
def build_model(vocab_size, embedding_dim, rnn_units, batch_size):
    model = keras.models.Sequential([ #定义模型
        keras.layers.Embedding(vocab_size, embedding_dim, #定义embedding层
                               batch_input_shape = [batch_size, None]), # 指定输入的大小
        keras.layers.SimpleRNN(units = rnn_units, 
                               stateful = True,
                               recurrent_initializer = 'glorot_uniform',
                               return_sequences = True), #我们定义输入输出的时候，输入输出都是一个序列
                               # 我们模型要预测的也是一个序列，我的rnn返回的也是序列
        keras.layers.Dense(vocab_size), #全连接层，没有激活函数
    ])
    return model

model = build_model(
    vocab_size = vocab_size,
    embedding_dim = embedding_dim,
    rnn_units = rnn_units,
    batch_size = batch_size)

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (64, None, 256)           16640     
_________________________________________________________________
simple_rnn (SimpleRNN)       (64, None, 1024)          1311744   
_________________________________________________________________
dense (Dense)                (64, None, 65)            66625     
Total params: 1,395,009
Trainable params: 1,395,009
Non-trainable params: 0
_________________________________________________________________


In [0]:
for input_example_batch, target_example_batch in seq_dataset.take(1): #看下模型的输出是什么 使用的方法就是讲model当一个函数来用
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape) #batch_size 句子长度 词表长度（每个词的概率）

(64, 100, 65)


In [0]:
# random sampling. 我们做文本生成的时候都会得到一个概率分布，基于这个概率分布来随机采样
# greedy, random.
sample_indices = tf.random.categorical( # tf 随机采样。 logits 对于分类任务来说，在softmax之前的那个值就是logits
    logits = example_batch_predictions[0], num_samples = 1) # example_batch_predictions[0] size就是100^*65
    # num_samples = 1 表示生成一个序列，可以等于别的值 用随机采杨生成多个序列，返回采样数据的索引
print(sample_indices)
# (100, 65) -> (100, 1)
sample_indices = tf.squeeze(sample_indices, axis = -1) # 把（100 * 1）的维度里面的1去掉，这样shape变成shape=(100,)
print(sample_indices)

tf.Tensor(
[[18]
 [22]
 [22]
 [41]
 [24]
 [48]
 [42]
 [44]
 [37]
 [45]
 [ 6]
 [48]
 [ 6]
 [26]
 [36]
 [61]
 [ 8]
 [22]
 [63]
 [41]
 [20]
 [14]
 [20]
 [35]
 [57]
 [ 4]
 [61]
 [10]
 [10]
 [39]
 [34]
 [26]
 [43]
 [52]
 [29]
 [29]
 [43]
 [48]
 [38]
 [11]
 [13]
 [ 1]
 [64]
 [64]
 [45]
 [52]
 [45]
 [21]
 [ 5]
 [15]
 [52]
 [35]
 [16]
 [34]
 [ 4]
 [24]
 [48]
 [ 4]
 [27]
 [19]
 [39]
 [27]
 [30]
 [43]
 [16]
 [60]
 [42]
 [29]
 [42]
 [43]
 [ 1]
 [60]
 [ 9]
 [11]
 [37]
 [37]
 [36]
 [51]
 [16]
 [28]
 [60]
 [47]
 [ 8]
 [57]
 [27]
 [14]
 [16]
 [17]
 [47]
 [56]
 [18]
 [21]
 [52]
 [34]
 [22]
 [19]
 [13]
 [60]
 [21]
 [47]], shape=(100, 1), dtype=int64)
tf.Tensor(
[18 22 22 41 24 48 42 44 37 45  6 48  6 26 36 61  8 22 63 41 20 14 20 35
 57  4 61 10 10 39 34 26 43 52 29 29 43 48 38 11 13  1 64 64 45 52 45 21
  5 15 52 35 16 34  4 24 48  4 27 19 39 27 30 43 16 60 42 29 42 43  1 60
  9 11 37 37 36 51 16 28 60 47  8 57 27 14 16 17 47 56 18 21 52 34 22 19
 13 60 21 47], shape=(100,), dtype=int64)


In [0]:
print("Input: ", repr("".join(idx2char[input_example_batch[0]])))
print()
print("Output: ", repr("".join(idx2char[target_example_batch[0]])))
print()
print("Predictions: ", repr("".join(idx2char[sample_indices])))

Input:  "'ertake his bad intent,\nAnd must be buried but as an intent\nThat perish'd by the way: thoughts are n"

Output:  "ertake his bad intent,\nAnd must be buried but as an intent\nThat perish'd by the way: thoughts are no"

Predictions:  "FJJcLjdfYg,j,NXw.JycHBHWs&w::aVNenQQejZ;A zzgngI'CnWDV&Lj&OGaOReDvdQde v3;YYXmDPvi.sOBDEirFInVJGAvIi"


In [0]:
def loss(labels, logits): #自定义的损失函数
    return keras.losses.sparse_categorical_crossentropy(
        labels, logits, from_logits=True) 
    # logits表示网络的直接输出 。没经过sigmoid或者softmax的概率化。
    # from_logits=False就表示把已经概率化了的输出，重新映射回原值。log（p/(1-p)）

model.compile(optimizer = 'adam', loss = loss)
example_loss = loss(target_example_batch, example_batch_predictions)
print(example_loss.shape)
print(example_loss.numpy().mean())

(64, 100)
4.1913624


In [0]:
output_dir = "./text_generation_checkpoints"
if not os.path.exists(output_dir):
    os.mkdir(output_dir)
checkpoint_prefix = os.path.join(output_dir, 'ckpt_{epoch}')
checkpoint_callback = keras.callbacks.ModelCheckpoint(
    filepath = checkpoint_prefix,
    save_weights_only = True) # 只保留参数的值

epochs = 100
history = model.fit(seq_dataset, epochs = epochs,
                    callbacks = [checkpoint_callback])


Epoch 1/100
172/172 [==============================] - 44s 258ms/step - loss: 2.6715
Epoch 2/100
172/172 [==============================] - 42s 247ms/step - loss: 2.0199
Epoch 3/100
172/172 [==============================] - 44s 253ms/step - loss: 1.8145
Epoch 4/100
172/172 [==============================] - 43s 249ms/step - loss: 1.6819
Epoch 5/100
172/172 [==============================] - 43s 252ms/step - loss: 1.5952
Epoch 6/100
172/172 [==============================] - 42s 243ms/step - loss: 1.5344
Epoch 7/100
172/172 [==============================] - 42s 242ms/step - loss: 1.4893
Epoch 8/100
172/172 [==============================] - 42s 244ms/step - loss: 1.4533
Epoch 9/100
172/172 [==============================] - 42s 242ms/step - loss: 1.4256
Epoch 10/100
172/172 [==============================] - 44s 255ms/step - loss: 1.3982
Epoch 11/100
172/172 [==============================] - 44s 255ms/step - loss: 1.3769
Epoch 12/100
172/172 [==============================] - 43s 250

In [0]:
tf.train.latest_checkpoint(output_dir)

'./text_generation_checkpoints/ckpt_100'

In [0]:
model2 = build_model(vocab_size,
                     embedding_dim,
                     rnn_units,
                     batch_size = 1) # 在checkpoint中载入模型，batch_size=1,在一次测试的时候，只测试一个样本
model2.load_weights(tf.train.latest_checkpoint(output_dir)) # 载入之前保存的权重
model2.build(tf.TensorShape([1, None])) #设置输入的size,在tensorflow中size都使用TensorShape, 1指的是一个样本，None指的是输入可以是一个变长的序列
# 文本生成的流程
# start ch sequence A,
# A -> model -> b
# A.append(b) -> B
# B(Ab) -> model -> c
# B.append(c) -> C
# C(Abc) -> model -> ...
model2.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 256)            16640     
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (1, None, 1024)           1311744   
_________________________________________________________________
dense_1 (Dense)              (1, None, 65)             66625     
Total params: 1,395,009
Trainable params: 1,395,009
Non-trainable params: 0
_________________________________________________________________


In [0]:
def generate_text(model, start_string, num_generate = 1000): 
    input_eval = [char2idx[ch] for ch in start_string] #把start_string变成id
    input_eval = tf.expand_dims(input_eval, 0)
    
    text_generated = [] #生成的字符id
    model.reset_states()
    
    for _ in range(num_generate):
        # 1. model inference -> predictions
        # 2. sample -> ch -> text_generated.
        # 3. update input_eval
        
        # predictions : [batch_size, input_eval_len, vocab_size]
        predictions = model(input_eval) 
        # predictions : [input_eval_len, vocab_size]
        predictions = tf.squeeze(predictions, 0) #消掉第0维
        # predicted_ids: [input_eval_len, 1]
        # a b c -> b c d
        predicted_id = tf.random.categorical(
            predictions, num_samples = 1)[-1, 0].numpy() #随机sample
        text_generated.append(idx2char[predicted_id])
        # s, x -> rnn -> s', y
        input_eval = tf.expand_dims([predicted_id], 0)
    return start_string + ''.join(text_generated)

new_text = generate_text(model2, "All: ")
print(new_text)


All: his face beauty's slanders. Well, and some unto the storm'd fear; then dreams.

CORIOLANUS:
I will be made;
Rike unwilling I will purposed-head:
And I will stir the man
And all the from your parciur flies by himself. Well;
I am the widows fair? s, Auch
An utterance on many lines, I'ld s, and thou never ed.
Some happy stride, and supll you want fairest twenty soled no geedle moise his own alone! I am toUS:
Hair undood oppasies? Or Your issues sir,
That lies alenty; and therefore from your wealth.

ROMEO:
As I beleavent an England.

TYBALT:
My love: be of thee the flesh long-prounds. Grace now, gentle more than Jove, my gracious souls,
Brief, his father,
As, by some instery assurakery live,
And finderape.

CARESLENT:
My lord of France?
Why, what I had sees to Rome, name myself; it wass'd, being all eet and being sudd it yet?

RAMILANUS:
Now, brother Clarence.
Of all run arms
By Bianciau-house your grandsistail.

PETRUCHIO:
Come, content ines, it is here?
This day, my lord, will you 